version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: contador_loja_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: contador_loja
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:
