spring.datasource.url=jdbc:mysql://localhost:3307/contador_loja
spring.datasource.username=app_user
spring.datasource.password=app_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
