# Pega o perfil ativo do .env, se não achar, usa 'dev' como padrão
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Configurações do Cloudinary (Puxando do .env)
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

